resource_group_name = "dev_Organization"
virtual_network_name = "dev_vnetprod"
subnet_name = "dev_subnet"
network_interface_name = "dev_nicprod"
public_ip_name = "dev_publicip"
virtual_machine_name = "dev_linuxVM"
